parameters:
    uploads_dir: '%kernel.project_dir%/public/uploads'

services:
    # Configuration par défaut pour tous les services de ce fichier
    _defaults:
        autowire: true        # Injection automatique des dépendances
        autoconfigure: true   # Enregistrement automatique des services utiles (Controller, Command, etc.)

    # Enregistrement automatique de tous les services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration spécifique pour HomeController (injection de $uploadsDir)
    App\Controller\HomeController:
        arguments:
            $uploadsDir: '%uploads_dir%'